catalogMode: prefer
shellEmulator: true
trustPolicy: no-downgrade

catalog:
  '@antfu/eslint-config': ^9.0.0
  '@eslint/eslintrc': ^3.3.5
  '@types/fs-extra': ^11.0.4
  '@types/node': ^24.12.2
  bumpp: ^11.0.1
  eslint: ^10.2.1
  eslint-flat-config-utils: ^3.1.0
  execa: ^9.6.1
  fast-glob: ^3.3.3
  fs-extra: ^11.3.4
  local-pkg: ^1.1.2
  tsdown: ^0.21.10
  tsx: ^4.21.0
  typescript: ^5.9.3
  vitest: ^4.1.5
configDependencies:
  '@pnpm/plugin-trusted-deps': 0.2.2+sha512-+ZupiXKJhW2fbSilfyRp+wrAY54MKg+c0JWSFGdeb/y9bUoYN5u4XLOZ0Txk7O2bBa6NMhWrX5mwmsHP3/nm9Q==
