catalogMode: prefer
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

configDependencies:
  '@pnpm/plugin-trusted-deps': ^0.2.2

allowBuilds:
  esbuild: true

catalog:
  '@antfu/eslint-config': ^9.5.1
  '@eslint/eslintrc': ^3.3.7
  '@types/node': ^26.4.1
  bumpp: ^12.3.0
  eslint: ^10.9.1
  eslint-flat-config-utils: ^3.2.0
  local-pkg: ^1.2.1
  tinyexec: ^1.3.1
  tinyglobby: ^0.2.17
  tsdown: ^0.22.14
  typescript: ^6.0.3
  vitest: ^4.1.11
