export const rootOder = {
  order: [
    'name',
    'appid',
    'description',
    'locale',
    'versionName',
    'versionCode',
    'networkTimeout',
    'debug',
    'uniStatistics',
    'app-plus',
    'h5',
    'quickapp',
    'mp-weixin',
    'mp-alipay',
    'mp-baidu',
    'mp-toutiao',
    'mp-lark',
    'mp-qq',
    'mp-kuaishou',
  ],
  pathPattern: '^$',
}
